// THIS IS A SAMPLE FILE. 

var testSuiteProps = 
[ { name: "errors", value: "0"},
{ name: "failures", value: "0"},
{ name: "hostname", value: "Trajan"},
{ name: "name", value: "JUnit Jupiter"},
{ name: "skipped", value: "0"},
{ name: "tests", value: "29"},
{ name: "time", value: "0.1"},
{ name: "timestamp", value: "2017-04-02T09:47:32"} ]
;
var sysprops = 
[ { name: "awt.toolkit", value: "sun.awt.X11.XToolkit"},
{ name: "file.encoding", value: "UTF-8"},
{ name: "file.encoding.pkg", value: "sun.io"},
{ name: "file.separator", value: "/"},
{ name: "java.awt.graphicsenv", value: "sun.awt.X11GraphicsEnvironment"},
{ name: "java.awt.printerjob", value: "sun.print.PSPrinterJob"},
{ name: "java.class.path", value: "/home/ebola/git/junit-dataprovider/build/classes/test:/home/ebola/git/junit-dataprovider/build/resources/test:/home/ebola/git/junit-dataprovider/build/classes/main:/home/ebola/git/junit-dataprovider/build/resources/main:/home/ebola/.gradle/caches/modules-2/files-2.1/org.junit.jupiter/junit-jupiter-api/5.0.0-M4/50f95d68c674a30374c5f50e6ad5212d2c1a3cec/junit-jupiter-api-5.0.0-M4.jar:/home/ebola/.gradle/caches/modules-2/files-2.1/org.junit.jupiter/junit-jupiter-engine/5.0.0-M4/10e0dc41a4e9c1817c2b729c3a7c48b1ddfed17/junit-jupiter-engine-5.0.0-M4.jar:/home/ebola/.gradle/caches/modules-2/files-2.1/org.opentest4j/opentest4j/1.0.0-M2/e2caa64702a83336d3dd32c7f69c1f092156df6d/opentest4j-1.0.0-M2.jar:/home/ebola/.gradle/caches/modules-2/files-2.1/org.junit.platform/junit-platform-commons/1.0.0-M4/359eb461814bd7356de541d131d45473d394a168/junit-platform-commons-1.0.0-M4.jar:/home/ebola/.gradle/caches/modules-2/files-2.1/org.junit.platform/junit-platform-engine/1.0.0-M4/5e65bdd2d623dfc6a405911a6449f2c60808b0af/junit-platform-engine-1.0.0-M4.jar:/home/ebola/.gradle/caches/modules-2/files-2.1/org.junit.platform/junit-platform-launcher/1.0.0-M4/d4e3657bc7cf204d6b9b55f0387fedc6eaad55fa/junit-platform-launcher-1.0.0-M4.jar:/home/ebola/.gradle/caches/modules-2/files-2.1/org.junit.platform/junit-platform-console/1.0.0-M4/82da9da502b1fe187bed5f5152746696aad19fae/junit-platform-console-1.0.0-M4.jar"},
{ name: "java.class.version", value: "52.0"},
{ name: "java.endorsed.dirs", value: "/usr/lib/jvm/java-8-oracle/jre/lib/endorsed"},
{ name: "java.ext.dirs", value: "/usr/lib/jvm/java-8-oracle/jre/lib/ext:/usr/java/packages/lib/ext"},
{ name: "java.home", value: "/usr/lib/jvm/java-8-oracle/jre"},
{ name: "java.io.tmpdir", value: "/tmp"},
{ name: "java.library.path", value: "/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib"},
{ name: "java.runtime.name", value: "Java(TM) SE Runtime Environment"},
{ name: "java.runtime.version", value: "1.8.0_121-b13"},
{ name: "java.specification.name", value: "Java Platform API Specification"},
{ name: "java.specification.vendor", value: "Oracle Corporation"},
{ name: "java.specification.version", value: "1.8"},
{ name: "java.vendor", value: "Oracle Corporation"},
{ name: "java.vendor.url", value: "http://java.oracle.com/"},
{ name: "java.vendor.url.bug", value: "http://bugreport.sun.com/bugreport/"},
{ name: "java.version", value: "1.8.0_121"},
{ name: "java.vm.info", value: "mixed mode"},
{ name: "java.vm.name", value: "Java HotSpot(TM) 64-Bit Server VM"},
{ name: "java.vm.specification.name", value: "Java Virtual Machine Specification"},
{ name: "java.vm.specification.vendor", value: "Oracle Corporation"},
{ name: "java.vm.specification.version", value: "1.8"},
{ name: "java.vm.vendor", value: "Oracle Corporation"},
{ name: "java.vm.version", value: "25.121-b13"},
{ name: "line.separator", value: " "},
{ name: "os.arch", value: "amd64"},
{ name: "os.name", value: "Linux"},
{ name: "os.version", value: "4.4.0-70-generic"},
{ name: "path.separator", value: ":"},
{ name: "sun.arch.data.model", value: "64"},
{ name: "sun.boot.class.path", value: "/usr/lib/jvm/java-8-oracle/jre/lib/resources.jar:/usr/lib/jvm/java-8-oracle/jre/lib/rt.jar:/usr/lib/jvm/java-8-oracle/jre/lib/sunrsasign.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jsse.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jce.jar:/usr/lib/jvm/java-8-oracle/jre/lib/charsets.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jfr.jar:/usr/lib/jvm/java-8-oracle/jre/classes"},
{ name: "sun.boot.library.path", value: "/usr/lib/jvm/java-8-oracle/jre/lib/amd64"},
{ name: "sun.cpu.endian", value: "little"},
{ name: "sun.cpu.isalist", value: ""},
{ name: "sun.desktop", value: "gnome"},
{ name: "sun.io.unicode.encoding", value: "UnicodeLittle"},
{ name: "sun.java.command", value: "org.junit.platform.console.ConsoleLauncher --details NONE --scan-class-path /home/ebola/git/junit-dataprovider/build/classes/main:/home/ebola/git/junit-dataprovider/build/resources/main:/home/ebola/git/junit-dataprovider/build/classes/test:/home/ebola/git/junit-dataprovider/build/resources/test -n ^.*Tests?$ --reports-dir /home/ebola/git/junit-dataprovider/build/test-results/junit-platform"},
{ name: "sun.java.launcher", value: "SUN_STANDARD"},
{ name: "sun.jnu.encoding", value: "UTF-8"},
{ name: "sun.management.compiler", value: "HotSpot 64-Bit Tiered Compilers"},
{ name: "sun.os.patch.level", value: "unknown"},
{ name: "user.country", value: "GB"},
{ name: "user.dir", value: "/home/ebola/git/junit-dataprovider"},
{ name: "user.home", value: "/home/ebola"},
{ name: "user.language", value: "en"},
{ name: "user.name", value: "ebola"},
{ name: "user.timezone", value: "Australia/Melbourne"},
{ name: "user.variant", value: ""} ]
;
var tests = [
{ testClass: "com.kncept.junit.dataprovider.testfactory.ParameterisedMethodTestFactoryTest", testName: "canCreateTests()", duration: "0.001", status: "Passed"},
{ testClass: "com.kncept.junit.dataprovider.testfactory.ParameterisedMethodTestFactoryTest", testName: "canExecuteTests()", duration: "0.001", status: "Passed"},
{ testClass: "com.kncept.junit.dataprovider.util.ReflectionUtilTest", testName: "canFindAnnotations()", duration: "0.003", status: "Passed"},
{ testClass: "com.kncept.junit.dataprovider.util.ReflectionUtilTest", testName: "canFindAnnotationsOnOverriddenMethods()", duration: "0.001", status: "Passed"},
{ testClass: "com.kncept.junit.dataprovider.util.ReflectionUtilTest", testName: "canFindMultipleAnnotations()", duration: "0.001", status: "Passed"},
{ testClass: "com.kncept.junit.dataprovider.testfactory.ParameterisedMethodTestFactoryTest", testName: "canFindSourceMethods()", duration: "0", status: "Passed"},
{ testClass: "com.kncept.junit.dataprovider.testfactory.ParameterisedMethodTestFactoryTest", testName: "canFindTestMethods()", duration: "0.001", status: "Passed"},
{ testClass: "com.kncept.junit.dataprovider.testfactory.ParameterisedMethodTestFactoryTest", testName: "canLookupSourceMethods()", duration: "0", status: "Passed"},
{ testClass: "testFactory()", testName: "day is propercase: Friday", duration: "0", status: "Passed"},
{ testClass: "testFactory()", testName: "day is propercase: Monday", duration: "0.001", status: "Passed"},
{ testClass: "testFactory()", testName: "day is propercase: Saturday", duration: "0", status: "Passed"},
{ testClass: "testFactory()", testName: "day is propercase: Sunday", duration: "0.004", status: "Passed"},
{ testClass: "testFactory()", testName: "day is propercase: Thursday", duration: "0", status: "Passed"},
{ testClass: "testFactory()", testName: "day is propercase: Tuesday", duration: "0.001", status: "Passed"},
{ testClass: "testFactory()", testName: "day is propercase: Wednesday", duration: "0", status: "Passed"},
{ testClass: "com.kncept.junit.dataprovider.testfactory.ParameterisedMethodTestFactoryTest", testName: "disabledTestsAreIgnored()", duration: "0.001", status: "Passed"},
{ testClass: "com.kncept.junit.dataprovider.testfactory.ParameterisedMethodTestFactoryTest", testName: "exceptionTypesAreRetained()", duration: "0.002", status: "Passed"},
{ testClass: "testFactory()", testName: "isADayOFTheWeek Friday", duration: "0.001", status: "Passed"},
{ testClass: "testFactory()", testName: "isADayOFTheWeek Monday", duration: "0.001", status: "Passed"},
{ testClass: "testFactory()", testName: "isADayOFTheWeek Saturday", duration: "0.001", status: "Passed"},
{ testClass: "testFactory()", testName: "isADayOFTheWeek Sunday", duration: "0.002", status: "Passed"},
{ testClass: "testFactory()", testName: "isADayOFTheWeek Thursday", duration: "0", status: "Passed"},
{ testClass: "testFactory()", testName: "isADayOFTheWeek Tuesday", duration: "0", status: "Passed"},
{ testClass: "testFactory()", testName: "isADayOFTheWeek Wednesday", duration: "0", status: "Passed"},
{ testClass: "integTest.com.kncept.junit.dataprovider.ExampleUseCasesTest", testName: "itsOkayToMixNormalTestAnnotations()", duration: "0.014", status: "Passed"},
{ testClass: "com.kncept.junit.dataprovider.util.ReflectionUtilTest", testName: "noAnnotationsToFind()", duration: "0.001", status: "Passed"},
{ testClass: "com.kncept.junit.dataprovider.testfactory.ParameterisedMethodTestFactoryTest", testName: "testNamesCanBeDefaulted()", duration: "0.001", status: "Passed"},
{ testClass: "com.kncept.junit.dataprovider.testfactory.ParameterisedMethodTestFactoryTest", testName: "testNamesCanBeSpecified()", duration: "0.003", status: "Passed"},
{ testClass: "com.kncept.junit.dataprovider.testfactory.ParameterisedMethodTestFactoryTest", testName: "throwsExceptionOnInvalidSourceMethodLookup()", duration: "0.002", status: "Passed"}
];
var summary = { passed: "29", skipped: "0", failed: "0", errored: "0", available: "29", executed: "29", timestamp: "2017-04-02T09:47:32", duration: "0.1"};
var packageSummary = [
{ key: "", passed: "14", skipped: "0", failed: "0", errored: "0", available: "14", executed: "14"},
{ key: "com.kncept.junit.dataprovider.testfactory", passed: "10", skipped: "0", failed: "0", errored: "0", available: "10", executed: "10"},
{ key: "com.kncept.junit.dataprovider.util", passed: "4", skipped: "0", failed: "0", errored: "0", available: "4", executed: "4"},
{ key: "integTest.com.kncept.junit.dataprovider", passed: "1", skipped: "0", failed: "0", errored: "0", available: "1", executed: "1"}
];
var classSummary = [
{ key: "com.kncept.junit.dataprovider.testfactory.ParameterisedMethodTestFactoryTest", passed: "10", skipped: "0", failed: "0", errored: "0", available: "10", executed: "10"},
{ key: "com.kncept.junit.dataprovider.util.ReflectionUtilTest", passed: "4", skipped: "0", failed: "0", errored: "0", available: "4", executed: "4"},
{ key: "integTest.com.kncept.junit.dataprovider.ExampleUseCasesTest", passed: "1", skipped: "0", failed: "0", errored: "0", available: "1", executed: "1"},
{ key: "testFactory()", passed: "14", skipped: "0", failed: "0", errored: "0", available: "14", executed: "14"}
];
